import PDFDocument from "pdfkit";

export const generatePdf = async (generatedDoc) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    // collect chunks
    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    // ─── Header ───
    doc.fontSize(24).fillColor("#111111").text(generatedDoc.title, { align: "center" });
    doc.moveDown(0.5);
    doc
      .fontSize(11)
      .fillColor("#666666")
      .text(`Type: ${generatedDoc.type}`, { align: "center" });
    doc.moveDown(2);

    // ─── Body ───
    const hasStructuredSteps =
      Array.isArray(generatedDoc.structuredSteps) &&
      generatedDoc.structuredSteps.length > 0;

    if (hasStructuredSteps) {
      // SOP / structured doc
      generatedDoc.structuredSteps.forEach((step) => {
        doc
          .fontSize(14)
          .fillColor("#4F46E5")
          .text(`Step ${step.step}: ${step.title || step.description}`);

        if (step.description) {
          doc
            .fontSize(11)
            .fillColor("#333333")
            .text(step.description);
        }

        if (step.role) {
          doc
            .fontSize(11)
            .fillColor("#555555")
            .text(`Role: ${step.role}`);
        }

        if (step.duration) {
          doc
            .fontSize(11)
            .fillColor("#555555")
            .text(`Duration: ${step.duration}`);
        }

        if (step.warning) {
          doc
            .fontSize(11)
            .fillColor("#D97706")
            .text(`⚠ Warning: ${step.warning}`);
        }

        doc.moveDown();
      });
    } else if (generatedDoc.content) {
      // Plain-text doc (Resume, Notes, Reports, Articles, etc.)
      doc
        .fontSize(11)
        .fillColor("#333333")
        .text(generatedDoc.content, {
          align: "left",
          lineGap: 4,
        });
    } else {
      doc.fontSize(11).fillColor("#999999").text("No content available.");
    }

    // ─── Footer ───
    doc.moveDown(2);
    doc
      .fontSize(10)
      .fillColor("#aaaaaa")
      .text("Generated by Document Generator", { align: "center" });

    doc.end();
  });
};